language: generic
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed akikoyuri/udagram-api-feed:v1
  - docker tag udagram-api-user akikoyuri/udagram-api-user:v1
  - docker tag udagram-frontend akikoyuri/udagram-frontend:v1
  - docker tag reverseproxy akikoyuri/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push akikoyuri/udagram-api-feed:v1
  - docker push akikoyura/udagram-api-user:v1
  - docker push akikoyura/udagram-frontend:v1
  - docker push akikoyura/reverseproxy:v1


